= puudoc document markup concept

Using `puu` markup.

....
include{some_file.puudoc}

defs{
    my_template{x y z
        {
            ==={ subheader }
            p{
                lorem ipsum ${x} dolor ${y} sit amet ${z} bla bla...
            }
        }
    }

    // variable is same as template without arguments, invoke as ${var_name}
    variable1{1.0.3}

    // array is same as variable, but with empty string element with children
    // elements with non-empty string will be substituted as is when accessed by index
    array{
        {element1 bla bla} {element2} {element3} {this is b{element} 4} {${variable}} sinle_word_element
        complex{element bla bla}
    }
}

={ header1 puudoc document markup concept }

=={ header2 puudoc code example }

p{
    Hello world! b{how are you doing today}? I'm fine, thanks!
    How about you? I'm fine too. Version ${variable1}.
}

// template with arguemnts can be invoked without ${}
my_template{ x{pre-dolor} y{pre-sit} z{pre-bla} }

p{
    Lorem i{ipsum} bi{dolor} sit amet bla bla.
    link{http://blabla.net}.
    image{my_image.png}
}

for{
    i{ from{3} to{size{array}}} step{2} }
    // or
    i{ in{ 3 4 6} }

    {
        my_tempplate{ x{${i}} y{array{${i}}} z{bye} }
    }
}

p{
    numbered list:
    .{ bla bla1 }
    .{ bla bla2 }
    .{ bla bla3 }

    unnumbered list:
    -{ bla bla }
    -{ bla bla }
    -{ bla bla }

}
....
