= curlydoc document markup concept

Using `treeml` markup.

....
include{some_file.cdoc}

// templates, variables and arrays are all same. Difference is only in the way how those are invoked.
// Template invokation must have at least one child with children.
// Array element access must have one childless child.
// Variable is invoked as ${var_name}.

defs{
    template my_template{
        args {x y z}
        body {
            ==={ subheader }
            p{
                lorem ipsum ${x} dolor ${y} sit amet ${z} bla bla...
            }
        }
    }

    // variable is same as template without arguments, invoke as ${var_name}
    var variable1{1.0.3}

    // array is same as variable, but with empty string element with children
    // elements with non-empty string will be substituted as is when accessed by index
    var array{
        {element1 bla bla} {element2} {element3} {this is b{element} 4} ${variable} sinle_word_element ""{trololo trololo}
        complex{element bla bla}
    }
}

// Template invocation:
my_template{x{bla} y{bal} z{lba}}
// or
my_template{bla bal lba}
// or
${my_template x{bla} y{bla} z{bla}}
// or
${my_template bla bal lba}

// array:
size{array} // size of array
array{10} // element access by index. Elements which are empty string with children will be unwrapped, i.e. only children will be substituted
${array 10}
${array} // this will substitute all array elements as is, without any unwrapping

={ header1 curlydoc document markup concept }

=={ header2 curlydoc code example }

p{
    Hello world! b{how are you doing today}? I'm fine, thanks!
    How ab +b+{o} ut you? I'm fine too. Version ${variable1}.
    // to link bold letter to left and right words use +
}

code{
    bla bla
}

`cpp{R"qwerty(
    multiline code
    snippet
)qwerty"}

// template with arguemnts can be invoked without ${}
my_template{ x{pre-dolor} y{pre-sit} z{pre-bla} }

p{
    Lorem i{ipsum} bi{dolor} sit `{amet} bla bla.
    link{http://blabla.net}.
    image{my_image.png}
}

for{
    i{ from{3} to{size{array}} step{2} }
    // or
    i{ in{ 3 4 6} }

    {
        my_tempplate{ x{${i}} y{array{${i}}} z{bye} }
    }
}

p{
    numbered list:
    .{ bla bla1 }
    .{ bla bla2 }
    .{ bla bla3 }

    unnumbered list:
    -{ bla bla }
    -{ bla bla }
    -{ bla bla }

}

....
