= curlydoc document markup concept

Using `treeml` markup.

....
include{some_file.cdoc}

// templates, variables and arrays are all same. Difference is only in the way how those are invoked.
// Template invokation must have at least one child with children.
// Array element access must have one childless child.
// Variable is invoked as ${var_name}.

defs{
    my_template{
        defs {${@}}
        
		==={ subheader }
		p{
			lorem ipsum ${x} dolor ${y} sit amet ${z} bla bla...
		}
    }

    // variable is same as template without arguments, invoke as ${var_name}
    variable1{1.0.3}

    // array is same as variable, but with empty string element with children
    // elements with non-empty string will be substituted as is when accessed by index
    array{
        {element1 bla bla} {element2} {element3} {this is b{element} 4} ${variable} sinle_word_element ""{trololo trololo}
        complex{element bla bla}
    }
}

// Template invocation:
my_template{x{bla} y{bal} z{lba}}

// array:
size{array} // size of array
${array 10} // element access by index. Elements which are empty string with children will be unwrapped, i.e. only children will be substituted
${array} // this will substitute all array elements as is, without any unwrapping

={ header1 curlydoc document markup concept }

=={ header2 curlydoc code example }

p{
    Hello world! b{how are you doing today}???? I'm fine, thanks!
    How ab _{+} b{o} _{+} ut you? I'm i{fine}, too. Version ${variable1}.
    // to link bold letter to left and right words using cmd{+}
	Some "quoted b{stuff}" whould work? Or should it be some \"quoted b{stuff}\"?
}

code{ { lang{cpp} } // the parameter block must be the first child empty string with children, it mabe absent
    bla bla
}
// alias: code=`
`{
    bla bla
}

// possible template for cpp code block
`cpp{R"qwerty(
    multiline code
    snippet
)qwerty"}

p{
    Lorem i{ipsum} bi{dolor} sit code{amet} bla bla.
    link{http://blabla.net}.
    image{my_image.png}
}

for{
    // the first child of the 'for' must be the iterator declaration
	i{ 3 4 6 }
    // or
	i{ range{from{3} to{size{array}} step{2}} }
	// or
	i{ {first one} {second one} third{one} }

    
    my_tempplate{ x{${i}} y{${array ${i}}} z{bye} }
}

p{
    numbered list:
    ol{
		{bla bla}
		{bla bla}
		{bla bla}
	}

    unnumbered list:
	ul{
		{bla bla bla}
		{bla bla bla}
	}

}

....
