include prorab.mk
include prorab-license.mk
include prorab-clang-format.mk

$(eval $(prorab-include-subdirs))

this_license_file := ../LICENSE
this_src_dir := .
$(eval $(prorab-license))

$(eval $(prorab-clang-format))
